[package]
name = "rivetx-example-rs"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "rivetx-example-rs"
path = "src/main.rs"


[dependencies]
rivetx-sql-derive-rs = { path = "../rivetx-sql-derive-rs" }
rivetx-sql-rs = { path = "../rivetx-sql-rs" }
rivetx-core-rs = { path = "../rivetx-core-rs" }
mysql_async = "0.34.2"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
serde = { version = "1.0", features = ["derive", "rc"] }
anyhow = { git = "https://github.com/yefy/anyhow.git" }
log4rs = { git = "https://github.com/yefy/log4rs.git" }
scopeguard = "1.2.0"
moka = { version = "0.12.10", features = ["sync", "future"] }
linked-hash-map = "0.5.6"
axum = "0.8.4"


[dependencies.serde_json]
version = "1"
features = [ "arbitrary_precision", "preserve_order" ]

[dependencies.log]
version = "0.4.20"
features = ["std"]
